table DimAccount
	lineageTag: 354393eb-51fe-4938-b4c6-e818989ec4a3

	column AccountID
		dataType: int64
		formatString: 0
		lineageTag: 5f832494-9f52-46ae-a9bb-5113d5a31565
		summarizeBy: none
		sourceColumn: AccountID

		annotation SummarizationSetBy = Automatic

	column AccountName
		dataType: string
		lineageTag: d48fc8a9-72c4-413b-acd0-f4dc7c8af253
		summarizeBy: none
		sourceColumn: AccountName

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		lineageTag: a7ef32aa-0a6d-44db-b27a-9ef21e187c9f
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: bc0a3e67-1ade-427b-802e-1a053db11ea7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column CompanySize
		dataType: string
		lineageTag: 8dbec023-cb1f-4bf1-9716-9cd310cff498
		summarizeBy: none
		sourceColumn: CompanySize

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 71fe11bc-a80f-48fc-8043-a6f8464d1343
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column SignupDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 73694042-c0ae-44b8-8dfb-e841916746e5
		summarizeBy: none
		sourceColumn: SignupDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CohortMonth
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: 24fa7210-d33f-49a5-9a73-1ef6bd77bb88
		summarizeBy: none
		sourceColumn: CohortMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DimAccount = m
		mode: import
		source =
				// DimAccount: one row per account, cleaned from accounts.csv
				// Fixes: duplicate rows, region spelling variants, mixed date formats, stray spaces/casing, blank company size
				let
				    Source = Csv.Document(File.Contents(DataFolder & "accounts.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				
				    // Standardise text: trim spaces, remove non-printing characters, fix casing
				    CleanText = Table.TransformColumns(Promoted, {
				        {"account_name", each Text.Trim(Text.Clean(_)), type text},
				        {"industry", each Text.Proper(Text.Trim(_)), type text},
				        {"region", each Text.Upper(Text.Trim(_)), type text},
				        {"acquisition_channel", each Text.Trim(_), type text}
				    }),
				
				    // Map every region spelling to one value; anything unexpected becomes "Unknown" so it is easy to spot
				    RegionMap = [
				        #"NORTH AMERICA" = "North America", #"N. AMERICA" = "North America", NA = "North America",
				        EMEA = "EMEA", EUROPE = "EMEA",
				        APAC = "APAC", #"ASIA PACIFIC" = "APAC",
				        LATAM = "LATAM", #"LATIN AMERICA" = "LATAM"
				    ],
				    FixRegion = Table.TransformColumns(CleanText, {{"region", each Record.FieldOrDefault(RegionMap, _, "Unknown"), type text}}),
				
				    // Most dates are yyyy-MM-dd, some are dd/MM/yyyy
				    ParseDate = (value as text) as date =>
				        if Text.Contains(value, "/")
				        then Date.FromText(value, [Format = "dd/MM/yyyy"])
				        else Date.FromText(value, [Format = "yyyy-MM-dd"]),
				    FixDates = Table.TransformColumns(FixRegion, {{"signup_date", ParseDate, type date}}),
				
				    FixSize = Table.ReplaceValue(FixDates, "", "Unknown", Replacer.ReplaceValue, {"company_size"}),
				    Typed = Table.TransformColumnTypes(FixSize, {{"account_id", Int64.Type}, {"company_size", type text}}),
				
				    // Remove duplicate accounts (keeps the first row per account_id)
				    Deduped = Table.Distinct(Typed, {"account_id"}),
				
				    AddCohort = Table.AddColumn(Deduped, "CohortMonth", each Date.StartOfMonth([signup_date]), type date),
				    Renamed = Table.RenameColumns(AddCohort, {
				        {"account_id", "AccountID"}, {"account_name", "AccountName"}, {"industry", "Industry"},
				        {"region", "Region"}, {"company_size", "CompanySize"}, {"acquisition_channel", "Channel"},
				        {"signup_date", "SignupDate"}
				    })
				in
				    Renamed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

